{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "id": "1qgtooAHKcZS"
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "id": "BrhZf0Q9Ksnz"
   },
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "id": "m0o0rXcpKsqP"
   },
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "File b'train.csv' does not exist",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-3-cd75a77447fc>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mdf\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread_csv\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'train.csv'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\u001b[0m in \u001b[0;36mparser_f\u001b[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)\u001b[0m\n\u001b[0;32m    676\u001b[0m                     skip_blank_lines=skip_blank_lines)\n\u001b[0;32m    677\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 678\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0m_read\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfilepath_or_buffer\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkwds\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    679\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    680\u001b[0m     \u001b[0mparser_f\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mname\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\u001b[0m in \u001b[0;36m_read\u001b[1;34m(filepath_or_buffer, kwds)\u001b[0m\n\u001b[0;32m    438\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    439\u001b[0m     \u001b[1;31m# Create the parser.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 440\u001b[1;33m     \u001b[0mparser\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mTextFileReader\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfilepath_or_buffer\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    441\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    442\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mchunksize\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0miterator\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, f, engine, **kwds)\u001b[0m\n\u001b[0;32m    785\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0moptions\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'has_index_names'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mkwds\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'has_index_names'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    786\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 787\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_make_engine\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mengine\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    788\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    789\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mclose\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\u001b[0m in \u001b[0;36m_make_engine\u001b[1;34m(self, engine)\u001b[0m\n\u001b[0;32m   1012\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_make_engine\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mengine\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'c'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1013\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mengine\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m'c'\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1014\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_engine\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mCParserWrapper\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mf\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0moptions\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1015\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1016\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mengine\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m'python'\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\pandas\\io\\parsers.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, src, **kwds)\u001b[0m\n\u001b[0;32m   1706\u001b[0m         \u001b[0mkwds\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'usecols'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0musecols\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1707\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1708\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_reader\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mparsers\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTextReader\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msrc\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1709\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1710\u001b[0m         \u001b[0mpassed_names\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mnames\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mpandas\\_libs\\parsers.pyx\u001b[0m in \u001b[0;36mpandas._libs.parsers.TextReader.__cinit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;32mpandas\\_libs\\parsers.pyx\u001b[0m in \u001b[0;36mpandas._libs.parsers.TextReader._setup_parser_source\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mFileNotFoundError\u001b[0m: File b'train.csv' does not exist"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('train.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 419
    },
    "id": "8cAk1kdYKst4",
    "outputId": "4949668a-40f8-4b24-d82a-2d40c8002005"
   },
   "outputs": [],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "qAJz37mgPGiJ"
   },
   "outputs": [],
   "source": [
    "df.drop('output',axis=1,inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "MZL5KNDEPTuf"
   },
   "outputs": [],
   "source": [
    "y = df['output']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "fKp0lDxIKswZ",
    "outputId": "fe2340ab-afab-4588-91c7-28666d5eaf4e"
   },
   "outputs": [],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "4sV1z61qKszk",
    "outputId": "dc01ee77-3338-4e23-ff19-9e3930b69f2f"
   },
   "outputs": [],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "sskrTkbOKs5Y",
    "outputId": "34a53951-c71a-472f-ed25-f2ae5c251d1a"
   },
   "outputs": [],
   "source": [
    "df['output'].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "40tePRSZKs8A",
    "outputId": "46622671-f0ae-46f0-9971-b4736a3cee36"
   },
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import StandardScaler\n",
    "standardized_data = StandardScaler().fit_transform(df)\n",
    "print(standardized_data.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "tHItFkK8Ks_M"
   },
   "outputs": [],
   "source": [
    "df2 = pd.DataFrame(standardized_data,columns =df.columns)\n",
    "df2['output']=y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "9fV1PmxSKtBo"
   },
   "outputs": [],
   "source": [
    "x = df2\n",
    "Y =df2.pop('output')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "jwJhZu8CKtEf"
   },
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(x,Y, test_size = 0.2, random_state=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "W_Si_QfbKtHd",
    "outputId": "76efb54f-21ab-46f8-b8a4-8bfbd1646cd3"
   },
   "outputs": [],
   "source": [
    "print(X_train.shape, y_test.shape)\n",
    "print( X_test.shape, y_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "1Fmh4KzhNR22",
    "outputId": "610fd439-8d50-442b-9ef1-5cb1a571152b"
   },
   "outputs": [],
   "source": [
    "from sklearn.linear_model import LogisticRegression\n",
    "classifier = LogisticRegression()\n",
    "classifier.fit(X_train,y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "vdzaJrXNNSGB"
   },
   "outputs": [],
   "source": [
    "y_pred = classifier.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "cHqgxdebNSST",
    "outputId": "164bbf8e-5d87-4f6a-fc32-b18aac5e4b7b"
   },
   "outputs": [],
   "source": [
    "from sklearn import metrics\n",
    "print(metrics.accuracy_score(y_test, y_pred))\n",
    "print(metrics.precision_score(y_test,y_pred))\n",
    "print(metrics.roc_auc_score(y_test,y_pred))\n",
    "print(metrics.f1_score(y_test,y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "IpbpoR_VNSeX",
    "outputId": "10e3e808-53d1-460a-cecd-470ca7ec387c"
   },
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'metrics' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-4-0c8befa3963b>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mcon_metric\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmetrics\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconfusion_matrix\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my_test\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_pred\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[0mcon_metric\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'metrics' is not defined"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\Anaconda3\\lib\\asyncio\\selector_events.py\", line 125, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    }
   ],
   "source": [
    "con_metric = metrics.confusion_matrix(y_test, y_pred)\n",
    "con_metric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 281
    },
    "id": "xhXusRPJNSoi",
    "outputId": "99444330-9a19-4787-f41e-01d24da4bd64"
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWAAAAEICAYAAABhxi57AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAXYElEQVR4nO3dfbxVZZ338c/3gCA+ICAjDwcMCrJxapy6zbSmxnQSMBR85eBDKXlzz7mbtOyuhqx8pVPZ5NRt6dxWcxoRzEQpa6AkH6LSrDSwfODBBEXkHCB8GLXUhHP27/5jr4Ob0zl777PP5lzsxffN63qdva61zrV+B/HHj2tday1FBGZmNvCaUgdgZravcgI2M0vECdjMLBEnYDOzRJyAzcwScQI2M0vECdh2kTRM0g8kPSfpO/0Y572Sbq9nbClI+pGkuanjsPxyAm5Aks6WtErSHyVtzRLF39Zh6NOBMcChEfEPtQ4SEd+OiJPqEM9uJB0vKSR9v1v/UVn/z6oc51JJ11c6LiJmRMSiGsM1q8gJuMFI+ijwVeALFJPl4cDXgFl1GP5VwCMR0VGHsfaUJ4HjJB1a0jcXeKReJ1CR/9+wPS8i3BqkAYcAfwT+ocwxQykm6C1Z+yowNNt3PNAGfAzYDmwFzsv2/QuwA9iZnWMecClwfcnYk4AABmfb7wceA/4AbATeW9J/d8n3vRVYCTyXfX1ryb6fAZ8DfpGNczswupefrSv+bwDnZ32DgHbgM8DPSo69EtgMPA/cB7w965/e7ed8oCSOy7I4XgKmZH3/K9v/deDmkvEvB1YASv3nwq1xm/+WbyzHAfsD3y9zzKeBY4G/AY4CjgEuLtk/lmIib6aYZK+WNDIiLqFYVd8UEQdFxDXlApF0IHAVMCMiDqaYZO/v4bhRwC3ZsYcCVwC3dKtgzwbOAw4DhgAfL3du4Drg3OzzNGA1xb9sSq2k+HswCrgB+I6k/SPi1m4/51El33MO0AIcDGzqNt7HgDdIer+kt1P8vZsbEb6X32rmBNxYDgWeivJTBO8FPhsR2yPiSYqV7Tkl+3dm+3dGxHKKVeARNcZTAF4vaVhEbI2INT0c825gfUR8KyI6ImIx8DBwSskx10bEIxHxErCEYuLsVUT8Ehgl6QiKifi6Ho65PiKezs75fyn+y6DSz7kwItZk37Oz23gvUvx9vAK4HvhQRLRVGM+sLCfgxvI0MFrS4DLHjGf36m1T1rdrjG4J/EXgoL4GEhEvAGcAHwC2SrpF0uuqiKcrpuaS7W01xPMt4ALgnfTwLwJJH5e0LlvR8SzFqn90hTE3l9sZEfdSnHIRxb8ozPrFCbix/Ap4GZhd5pgtFC+mdTmcP//nebVeAA4o2R5bujMibouIdwHjKFa136winq6Y2muMqcu3gA8Cy7PqdJdsimA+MAcYGREjKM4/qyv0XsYsO50g6XyKlfSWbHyzfnECbiAR8RzFi01XS5ot6QBJ+0maIenfssMWAxdL+gtJo7PjKy656sX9wDskHS7pEOCTXTskjZE0K5sLfpniVEahhzGWA6/Nls4NlnQGcCTwwxpjAiAiNgJ/R3HOu7uDgQ6KKyYGS/oMMLxk/++BSX1Z6SDptcDngfdRnIqYL6nsVIlZJU7ADSabz/woxQtrT1L8Z/MFwH9lh3weWAU8CDwE/Cbrq+VcdwA3ZWPdx+5JsymLYwvwDMVk+E89jPE0MJPiRaynKVaOMyPiqVpi6jb23RHRU3V/G3ArxaVpm4A/sfv0QtdNJk9L+k2l82RTPtcDl0fEAxGxHvgU8C1JQ/vzM9i+Tb6Ia2aWhitgM7NEnIDNzBJxAjYzS8QJ2MwskXIL+utzgiHNvspnf2b7jCmpQ7C90Kild6ryUeXtfOqxqnPOfqNf3e/z9YcrYDOzRPZ4BWxmNqAKnakjqJoTsJnlS+fe/Djr3TkBm1muRPR0R/zeyQnYzPKl4ARsZpaGK2Azs0R8Ec7MLBFXwGZmaYRXQZiZJeKLcGZmiXgKwswsEV+EMzNLxBWwmVkivghnZpaIL8KZmaUR4TlgM7M0PAdsZpaIpyDMzBJxBWxmlkjnztQRVM3vhDOzfCkUqm8VSFogabuk1T3s+5ikkDQ625akqyRtkPSgpDdVGt8J2MzyJQrVt8oWAtO7d0qaCJwEPFHSPQOYmrUW4OuVBncCNrN8qWMFHBF3Ac/0sOsrwHwgSvpmAddF0T3ACEnjyo3vBGxm+dKHBCypRdKqktZSaXhJs4D2iHig265mYHPJdlvW1ytfhDOzXIk+XISLiFagtdrjJR0AfIri9EO/OQGbWb7s2WVorwEmAw9IApgA/EbSMUA7MLHk2AlZX6+cgM0sX/bgjRgR8RBwWNe2pMeBoyPiKUnLgAsk3Qi8BXguIraWG89zwGaWL3VcBSFpMfAr4AhJbZLmlTl8OfAYsAH4JvDBSuO7AjazfKljBRwRZ1XYP6nkcwDn92V8J2AzyxffimxmlkiHH8huZpaGK2Azs0T8OEozs0RcAZuZJeIK2MwsEVfAZmaJeBWEmVkiEZWP2Us4AZtZvngO2MwsESdgM7NEfBHOzCyRzs7UEVTNCdjM8sVTEGZmiTgBm5kl4jlgM7M0ouB1wGZmaTTQFITfCWdm+dLZWX2rQNICSdslrS7p+5KkhyU9KOn7kkaU7PukpA2SfidpWqXxnYDNLF8KhepbZQuB6d367gBeHxF/DTwCfBJA0pHAmcBfZd/zNUmDyg3uBGxm+VLHBBwRdwHPdOu7PSK6nvhzDzAh+zwLuDEiXo6IjRTfjnxMufGdgAfItJOOZ83qu3h47d3M/+c+vTjVcmTozPcw/KprGf7vCxl6yukADJr0GoZf/jWGX3ktB336X2HYAYmjbHAR1bf++5/Aj7LPzcDmkn1tWV+vnIAHQFNTE1ddeRkzT3kfbzjqnZxxxmz+8i+npg7LBtigwycz9KSZPP/xD/D8hfMY8ubjaBrbzIEXzOfF6/6D5y88jx33/Jxhp52ZOtTG1ocKWFKLpFUlraXa00j6NNABfLvWUCuugpD0OoqldVcmbweWRcS6Wk+6rznmzW/k0UcfZ+PGJwBYsmQpp54yjXXr1ieOzAZS04RX0fnIOtjxMgA7Vz/AkOPeQdP4CXSseQCAjgdWMuzSL/PSDQtShtrY+rAMLSJagda+nkLS+4GZwIkRu0rpdmBiyWETsr5ela2AJX0CuBEQ8OusCVgs6aK+Br2vGt88ls1tW3Ztt7VvZfz4sQkjshQ6n9jI4CP/Gh08HIYMZcj/OJam0YfRuflx9nvL3wIw5K3vpGn0YYkjbXB1XAXRE0nTgfnAqRHxYsmuZcCZkoZKmgxMpZgze1WpAp4H/FVE7OwWwBXAGuCLvQTYArQAaNAhNDUdWOE0ZvlXaNvES9+7gYMv/TLx8p/o2LgBCp28cNXlHPiPH2bYnHPZ8etfEDt3Vh7MehV1XAcsaTFwPDBaUhtwCcVVD0OBOyQB3BMRH4iINZKWAGspTk2cHxFls3ylBFwAxgObuvWPy/b1qLSsHzykuXFuS9lDtrRvY+KE8bu2JzSPY8uWbQkjslR2/Hg5O368HIBh7/tHCk8/SaH9Cf5w6ccBaBo/gSFHH5cyxMZXxzvhIuKsHrqvKXP8ZcBl1Y5fKQF/BFghaT2vXN07HJgCXFDtSfZ1K1fdz5Qpk5k0aSLt7duYM2cW55zrlRD7Ih0ygnjuWZpGH8aQ497O8/M/uKsPiWFzzuVPty5LHWZjy8uzICLiVkmvpbiWrfQi3MpKpbW9orOzkws/cjHLb7mBQU1NLFx0E2vXPpI6LEvgoE98jqbhw4mODl74j68SL/yRoTPfw/4nnwbAjnvuYseK5YmjbHAN9CwIxR5+gZ2nIKwn22dMSR2C7YVGLb1T/R3jhc+cWXXOOfCzN/b7fP3hh/GYWb7kZQrCzKzhNNAUhBOwmeVKPZeh7WlOwGaWL66AzcwScQI2M0vEr6U3M0vD74QzM0vFCdjMLBGvgjAzS8QVsJlZIk7AZmZpRKenIMzM0nAFbGaWhpehmZml4gRsZpZI40wBl38rsplZo4mOQtWtEkkLJG2XtLqkb5SkOyStz76OzPol6SpJGyQ9KOlNlcZ3AjazfCn0oVW2EJjere8iYEVETAVWZNsAMyi+in4qxbfCf73S4E7AZpYrUYiqW8WxIu4CnunWPQtYlH1eBMwu6b8uiu4BRkgaV258J2Azy5c+VMCSWiStKmktVZxhTERszT5vA8Zkn5t55e3xAG288jLjHvkinJnlSl+WoUVEK9Ba87kiQlLNyy5cAZtZvtR3Drgnv++aWsi+bs/624GJJcdNyPp65QRsZrkSHdW3Gi0D5maf5wJLS/rPzVZDHAs8VzJV0SNPQZhZrtTzrfSSFgPHA6MltQGXAF8ElkiaB2wC5mSHLwdOBjYALwLnVRrfCdjM8qWOCTgizupl14k9HBvA+X0Z3wnYzHKlnhXwnuYEbGa54gRsZpZIdCp1CFVzAjazXHEFbGaWSBRcAZuZJeEK2MwskQhXwGZmSbgCNjNLpOBVEGZmafginJlZIk7AZmaJROO8FNkJ2MzyxRWwmVkiXoZmZpZIp1dBmJml4QrYzCwRzwGbmSXiVRBmZok0UgXstyKbWa50FpqqbpVI+j+S1khaLWmxpP0lTZZ0r6QNkm6SNKTWWJ2AzSxXIqpv5UhqBj4MHB0RrwcGAWcClwNfiYgpwH8D82qN1QnYzHKlEKq6VWEwMEzSYOAAYCtwAvDdbP8iYHatsToBm1muRKjqJqlF0qqS1vLKONEOfBl4gmLifQ64D3g2Ijqyw9qA5lpj9UU4M8uVvqyCiIhWoLWnfZJGArOAycCzwHeA6f2P8BVOwJbEwddcmzoEy6kqpxaq8ffAxoh4EkDS94C3ASMkDc6q4AlAe60n8BSEmeVKHVdBPAEcK+kASQJOBNYCPwVOz46ZCyytNVYnYDPLlehDKztOxL0UL7b9BniIYr5sBT4BfFTSBuBQ4JpaY/UUhJnlSh2nIIiIS4BLunU/BhxTj/GdgM0sV/wwHjOzRBropchOwGaWL4ErYDOzJDo8BWFmloYrYDOzRDwHbGaWiCtgM7NEXAGbmSXS6QrYzCyNBnojkROwmeVLwRWwmVkaDfRSZCdgM8sXX4QzM0ukIE9BmJkl0Zk6gD5wAjazXPEqCDOzRLwKwswsEa+CMDNLpJGmIPxSTjPLlUIfWiWSRkj6rqSHJa2TdJykUZLukLQ++zqy1lidgM0sVzpVfavClcCtEfE64ChgHXARsCIipgIrsu2aOAGbWa7UqwKWdAjwDrLXzkfEjoh4FpgFLMoOWwTMrjVWJ2Azy5W+JGBJLZJWlbSWkqEmA08C10r6raT/lHQgMCYitmbHbAPG1BqrL8KZWa705ZVwEdEKtPayezDwJuBDEXGvpCvpNt0QESGp5oUXroDNLFfqeBGuDWiLiHuz7e9STMi/lzQOIPu6vdZYnYDNLFc6+9DKiYhtwGZJR2RdJwJrgWXA3KxvLrC01lg9BWFmuVLndcAfAr4taQjwGHAexcJ1iaR5wCZgTq2DOwGbWa7U83GUEXE/cHQPu06sx/hOwGaWK34esJlZIn4WhJlZIo30LAgnYDPLFT+Q3cwskUIDTUI4AZtZrvginJlZIo1T/zoBm1nOuAI2M0uko/Zn4ww4J2Azy5XGSb9OwGaWM56CMDNLxMvQzMwSaZz06wRsZjnjKQgzs0Q6G6gGdgI2s1xxBWxmlki4AjYzS8MVsP2ZaScdzxVXfJZBTU0suHYx//alq1OHZAPk4i9cwV2/+DWjRo7gv67/BgBXX3M9Ny+7lZEjDgHgwv89l3e89Rh+eNtPuPaGm3d97yOPbuQ7C/6d1732NUlib0T1XoYmaRCwCmiPiJmSJgM3AocC9wHnRMSOWsZ2Ah4ATU1NXHXlZUw/+Sza2rZyz6+W84Mf3s66detTh2YDYPbJ7+Ls95zKpz735d36zzljNuedffpufTOnncDMaScAxeT74Ys+6+TbR3tgAuJCYB0wPNu+HPhKRNwo6RvAPODrtQzs19IPgGPe/EYeffRxNm58gp07d7JkyVJOPWVa6rBsgBz9N2/gkOEH9/n7lt9xJzP+/u/2QET51kFU3SqRNAF4N/Cf2baAE4DvZocsAmbXGqsT8AAY3zyWzW1bdm23tW9l/PixCSOyvcHim3/Aaef+Exd/4Qqee/4Pf7b/1hV3cvK7jh/4wBpc9OGXpBZJq0paS7fhvgrM55Wp5UOBZyOiI9tuA5prjbXmBCzpvDL7dv1QhcILtZ7CLLfOOO3d/GjJAm5eeDV/cegovvT/vrnb/gfXPMyw/fdn6qsnpQmwgRX60CKiNSKOLmmtXeNImglsj4j79lSs/amA/6W3HaU/VFPTgf04RT5sad/GxAnjd21PaB7Hli3bEkZkqY0eNZJBgwbR1NTE6afOYPXaR3bb/6Mfe/qhVn2pgCt4G3CqpMcpXnQ7AbgSGCGp6/rZBKC91ljLJmBJD/bSHgLG1HrSfc3KVfczZcpkJk2ayH777cecObP4wQ9vTx2WJfTkU8/s+rzizl8y5dWv2rVdKBS47Sc/dwKuUV8q4HIi4pMRMSEiJgFnAj+JiPcCPwW6rp7OBZbWGmulVRBjgGnAf3frF/DLWk+6r+ns7OTCj1zM8ltuYFBTEwsX3cTabhWP5dc/X/JFVv72QZ599nlOnP0+PjjvHFb+9kF+t/4xEDSPHcMl8z+86/hV969m7GGjmdg8LmHUjasz9viNGJ8AbpT0eeC3wDW1DqQoE6yka4BrI+LuHvbdEBFnVzrB4CHNjXNbig2Yl7b8PHUIthfab/Sr1d8xzn7VaVXnnBs2fb/f5+uPshVwRMwrs69i8jUzG2i+FdnMLBHfimxmlojfiGFmloinIMzMEhmAVRB14wRsZrniKQgzs0R8Ec7MLBHPAZuZJeIpCDOzRMrd3bu3cQI2s1zxa+nNzBLxFISZWSKegjAzS8QVsJlZIl6GZmaWiG9FNjNLxFMQZmaJOAGbmSXSSKsg+vNaejOzvU6BqLqVI2mipJ9KWitpjaQLs/5Rku6QtD77OrLWWJ2AzSxXog+/KugAPhYRRwLHAudLOhK4CFgREVOBFdl2TTwFYWa50hn1eSBlRGwFtmaf/yBpHdAMzAKOzw5bBPyM4qvq+8wVsJnlSkRU3SS1SFpV0lp6GlPSJOCNwL3AmCw5A2wDxtQaqytgM8uVvqyCiIhWoLXcMZIOAm4GPhIRz0sq/f6QVPNVP1fAZpYrdZwDRtJ+FJPvtyPie1n37yWNy/aPA7bXGqsTsJnlSiGi6laOiqXuNcC6iLiiZNcyYG72eS6wtNZYPQVhZrlSx2dBvA04B3hI0v1Z36eALwJLJM0DNgFzaj2BE7CZ5UodV0HcDaiX3SfW4xxOwGaWK5WmFvYmTsBmlit+HKWZWSKugM3MEnEFbGaWSGd0pg6hak7AZpYrjfQ4SidgM8sVP5DdzCwRV8BmZol4FYSZWSJeBWFmlki9bkUeCE7AZpYrngM2M0vEc8BmZom4AjYzS8TrgM3MEnEFbGaWiFdBmJkl4otwZmaJNNIUhN+KbGa5UufX0k+X9DtJGyRdVO9YXQGbWa7UqwKWNAi4GngX0AaslLQsItbW5QQ4AZtZztRxDvgYYENEPAYg6UZgFtA4CbhjR3tvr3Xe50hqiYjW1HHY3sV/LuqrLzlHUgvQUtLVWvLfohnYXLKvDXhL/yN8heeAB1ZL5UNsH+Q/F4lERGtEHF3SBvQvQidgM7OetQMTS7YnZH114wRsZtazlcBUSZMlDQHOBJbV8wS+CDewPM9nPfGfi71QRHRIugC4DRgELIiINfU8hxpp0bKZWZ54CsLMLBEnYDOzRJyAB8ievqXRGo+kBZK2S1qdOhZLwwl4AJTc0jgDOBI4S9KRaaOyvcBCYHrqICwdJ+CBseuWxojYAXTd0mj7sIi4C3gmdRyWjhPwwOjplsbmRLGY2V7CCdjMLBEn4IGxx29pNLPG4wQ8MPb4LY1m1nicgAdARHQAXbc0rgOW1PuWRms8khYDvwKOkNQmaV7qmGxg+VZkM7NEXAGbmSXiBGxmlogTsJlZIk7AZmaJOAGbmSXiBGxmlogTsJlZIv8f7Xt2HT9+uB0AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light",
      "tags": []
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.heatmap(con_metric, annot=True, fmt='d')\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "Yj7MC83cRyek",
    "outputId": "ec414d2d-bbd7-43e7-e224-6bdfb620e303"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,\n",
       "    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',\n",
       "    max_iter=-1, probability=False, random_state=None, shrinking=True,\n",
       "    tol=0.001, verbose=False)"
      ]
     },
     "execution_count": 35,
     "metadata": {
      "tags": []
     },
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.svm import SVC\n",
    "classifier = SVC(kernel='rbf')\n",
    "classifier.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {
    "id": "a8aawJDLRzDB"
   },
   "outputs": [],
   "source": [
    "y_pred = classifier.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "dLtV7MmTRzlL",
    "outputId": "16ee6c41-14f8-4445-b692-463769298671"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.0\n",
      "1.0\n",
      "1.0\n",
      "1.0\n"
     ]
    }
   ],
   "source": [
    "from sklearn import metrics\n",
    "print(metrics.accuracy_score(y_test, y_pred))\n",
    "print(metrics.precision_score(y_test,y_pred))\n",
    "print(metrics.roc_auc_score(y_test,y_pred))\n",
    "print(metrics.f1_score(y_test,y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "lc_OGHkDRz0u",
    "outputId": "db19ad91-10c6-433b-b5bc-999236af4733"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 99,   0],\n",
       "       [  0, 157]])"
      ]
     },
     "execution_count": 38,
     "metadata": {
      "tags": []
     },
     "output_type": "execute_result"
    }
   ],
   "source": [
    "con_metric = metrics.confusion_matrix(y_test, y_pred)\n",
    "con_metric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 281
    },
    "id": "VH5qEn6YR0Mb",
    "outputId": "aa00a9da-0a9e-44d2-d9de-5ae59d85b05d"
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWAAAAEICAYAAABhxi57AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAXaElEQVR4nO3dfZxWdZ3/8dd7QBBvEJDlbgaDkmzdyq0109rKdBM0FHzk4k0p+eO3s21attWSlY90K9vc+lG6P6udVgQzUcpaKfEuujErDSxvuDFBEZkBwptVS02Ymc/+cZ3Bi2nmuq655pr5ch3eTx7fx1zne858z2cQP3z4nu85RxGBmZkNvobUAZiZ7a2cgM3MEnECNjNLxAnYzCwRJ2Azs0ScgM3MEnECtl0kjZD0A0nPSvpOP8Z5r6TbaxlbCpJukTQ3dRyWX07AdUjSWZJWSfqjpK1ZovjbGgx9GjAeODgi/r7aQSLi2xFxQg3i2Y2kYyWFpO936z8i6/9pheNcIunacsdFxIkRsbjKcM3KcgKuM5I+CnwV+AKFZHkI8DVgVg2GfwXwcES012CsgfIEcIykg4v65gIP1+oEKvD/GzbwIsKtThpwEPBH4O9LHDOcQoLekrWvAsOzfccCrcDHgO3AVuDcbN+/AjuAndk55gGXANcWjT0FCGBotv1+4FHgD8BG4L1F/XcVfd9bgJXAs9nXtxTt+ynwOeAX2Ti3A2N7+dm64v8GcF7WNwRoAz4D/LTo2MuBzcBzwL3A27L+Gd1+zvuL4rg0i+NF4NCs7/9m+78O3Fg0/mXACkCp/1y41W/z3/L15RhgX+D7JY75NHA08NfAEcBRwEVF+ydQSOSNFJLslZJGR8TFFKrqGyLigIi4qlQgkvYHrgBOjIgDKSTZ+3o4bgxwc3bswcAC4OZuFexZwLnAOGAY8PFS5wauAc7JPk8HVlP4y6bYSgq/B2OA64DvSNo3Im7t9nMeUfQ9ZwPNwIHApm7jfQx4naT3S3obhd+7uRHhe/mtak7A9eVg4MkoPUXwXuCzEbE9Ip6gUNmeXbR/Z7Z/Z0Qsp1AFHlZlPJ3AayWNiIitEbGmh2PeDayPiG9FRHtELAEeAk4uOubqiHg4Il4EllJInL2KiF8CYyQdRiERX9PDMddGxFPZOf8fhX8ZlPs5F0XEmux7dnYb7wUKv48LgGuBD0VEa5nxzEpyAq4vTwFjJQ0tccwkdq/eNmV9u8bolsBfAA7oayAR8TxwOvABYKukmyW9poJ4umJqLNreVkU83wLOB95JD/8ikPRxSeuyFR3PUKj6x5YZc3OpnRFxD4UpF1H4i8KsX5yA68uvgJeA2SWO2ULhYlqXQ/jzf55X6nlgv6LtCcU7I+K2iHgXMJFCVfvNCuLpiqmtypi6fAv4ILA8q053yaYI5gNzgNERMYrC/LO6Qu9lzJLTCZLOo1BJb8nGN+sXJ+A6EhHPUrjYdKWk2ZL2k7SPpBMl/Xt22BLgIkl/IWlsdnzZJVe9uA94u6RDJB0EfLJrh6TxkmZlc8EvUZjK6OxhjOXAq7Olc0MlnQ4cDvywypgAiIiNwDsozHl3dyDQTmHFxFBJnwFGFu3/PTClLysdJL0a+DzwPgpTEfMllZwqMSvHCbjOZPOZH6VwYe0JCv9sPh/47+yQzwOrgAeAB4HfZH3VnOsO4IZsrHvZPWk2ZHFsAZ6mkAz/qYcxngJmUriI9RSFynFmRDxZTUzdxr4rInqq7m8DbqWwNG0T8Cd2n17ousnkKUm/KXeebMrnWuCyiLg/ItYDnwK+JWl4f34G27vJF3HNzNJwBWxmlogTsJlZIk7AZmaJOAGbmSVSakF/TTw96x2+ymd/ZtwtG1KHYHug9h1tKn9UaTuffLTinLPP2Ff2+3z94QrYzCyRAa+AzcwGVWdH6ggq5gRsZvnSsSc/znp3TsBmlisRPd0Rv2dyAjazfOl0AjYzS8MVsJlZIr4IZ2aWiCtgM7M0wqsgzMwS8UU4M7NEPAVhZpaIL8KZmSXiCtjMLBFfhDMzS8QX4czM0ojwHLCZWRqeAzYzS8RTEGZmibgCNjNLpGNn6ggq5nfCmVm+dHZW3sqQtFDSdkmre9j3MUkhaWy2LUlXSNog6QFJbyw3vhOwmeVLdFbeylsEzOjeKWkycALweFH3icC0rDUDXy83uBOwmeVLDSvgiLgTeLqHXV8B5gNR1DcLuCYK7gZGSZpYanwnYDPLlz4kYEnNklYVteZyw0uaBbRFxP3ddjUCm4u2W7O+XvkinJnlSvThIlxEtAAtlR4vaT/gUxSmH/rNCdjM8mVgl6G9CpgK3C8JoAn4jaSjgDZgctGxTVlfr5yAzSxfBvBGjIh4EBjXtS3pMeDIiHhS0jLgfEnXA28Gno2IraXG8xywmeVLDVdBSFoC/Ao4TFKrpHklDl8OPApsAL4JfLDc+K6AzSxfalgBR8SZZfZPKfocwHl9Gd8J2Mzyxbcim5kl0u4HspuZpeEK2MwsET+O0swsEVfAZmaJuAI2M0vEFbCZWSJeBWFmlkhE+WP2EE7AZpYvngM2M0vECdjMLBFfhDMzS6SjI3UEFXMCNrN88RSEmVkiTsBmZol4DtjMLI3o9DpgM7M06mgKwu+EM7N86eiovJUhaaGk7ZJWF/V9SdJDkh6Q9H1Jo4r2fVLSBkm/kzS93PhOwGaWL52dlbfyFgEzuvXdAbw2Il4PPAx8EkDS4cAZwF9l3/M1SUNKDe4EbGb5UsMEHBF3Ak9367s9Irqe+HM30JR9ngVcHxEvRcRGCm9HPqrU+E7AA2T4zPcw8oqrGfkfixh+8mkADJnyKkZe9jVGXn41B3z632DEfomjtNSmn3Asa1bfyUNr72L+v/TphbrWm4jKW//9H+CW7HMjsLloX2vW1ysn4AEw5JCpDD9hJs99/AM8d8E8hr3pGBomNLL/+fN54Zr/5LkLzmXH3T9nxKlnpA7VEmpoaOCKyy9l5snv43VHvJPTT5/NX/7ltNRh1b8+VMCSmiWtKmrNlZ5G0qeBduDb1YZadhWEpNdQKK27MnkbsCwi1lV70rxraHoFHQ+vgx0vAbBz9f0MO+btNExqon3N/QC037+SEZd8mRevW5gyVEvoqDe9gUceeYyNGx8HYOnSmzjl5OmsW7c+cWR1rg/L0CKiBWjp6ykkvR+YCRwfsauUbgMmFx3WlPX1qmQFLOkTwPWAgF9nTcASSRf2Nei9RcfjGxl6+OvRgSNh2HCG/c3RNIwdR8fmx9jnzX8LwLC3vJOGseMSR2opTWqcwObWLbu2W9u2MmnShIQR5UQNV0H0RNIMYD5wSkS8ULRrGXCGpOGSpgLTKOTMXpWrgOcBfxURO7sFsABYA3yxlwCbgWaABa+fxtwpE8ucJl86Wzfx4veu48BLvky89CfaN26Azg6ev+Iy9v+HDzNizjns+PUviJ07yw9mZn0SNVwHLGkJcCwwVlIrcDGFVQ/DgTskAdwdER+IiDWSlgJrKUxNnBcRJbN8uQTcCUwCNnXrn5jt61FxWf/0rHfUz20pNbTjR8vZ8aPlAIx43z/Q+dQTdLY9zh8u+TgADZOaGHbkMSlDtMS2tG1jctOkXdtNjRPZsmVbwohyooZ3wkXEmT10X1Xi+EuBSysdv1wC/giwQtJ6Xr66dwhwKHB+pSfZG+mgUcSzz9AwdhzDjnkbz83/4K4+JEbMOYc/3bosdZiW0MpV93HooVOZMmUybW3bmDNnFmef45UQ/ZaXZ0FExK2SXk1hLVvxRbiV5Urrvd0Bn/gcDSNHEu3tPP+fXyWe/yPDZ76HfU86FYAdd9/JjhXLE0dpKXV0dHDBRy5i+c3XMaShgUWLb2Dt2odTh1X/6uhZEIoBfoHd3joFYaWNu2VD6hBsD9S+o039HeP5z5xRcc7Z/7PX9/t8/eGH8ZhZvuRlCsLMrO7U0RSEE7CZ5Uotl6ENNCdgM8sXV8BmZok4AZuZJeLX0puZpeF3wpmZpeIEbGaWiFdBmJkl4grYzCwRJ2AzszSiw1MQZmZpuAI2M0vDy9DMzFJxAjYzS6R+poBLvxXZzKzeRHtnxa0cSQslbZe0uqhvjKQ7JK3Pvo7O+iXpCkkbJD0g6Y3lxncCNrN86exDK28RMKNb34XAioiYBqzItgFOpPAq+mkU3gr/9XKDOwGbWa5EZ1Tcyo4VcSfwdLfuWcDi7PNiYHZR/zVRcDcwStLEUuM7AZtZvvShApbULGlVUWuu4AzjI2Jr9nkbMD773MjLb48HaOXllxn3yBfhzCxX+rIMLSJagJaqzxURkqpeduEK2MzypbZzwD35fdfUQvZ1e9bfBkwuOq4p6+uVE7CZ5Uq0V96qtAyYm32eC9xU1H9OthriaODZoqmKHnkKwsxypZZvpZe0BDgWGCupFbgY+CKwVNI8YBMwJzt8OXASsAF4ATi33PhOwGaWLzVMwBFxZi+7ju/h2ADO68v4TsBmliu1rIAHmhOwmeWKE7CZWSLRodQhVMwJ2MxyxRWwmVki0ekK2MwsCVfAZmaJRLgCNjNLwhWwmVkinV4FYWaWhi/CmZkl4gRsZpZI1M9LkZ2AzSxfXAGbmSXiZWhmZol0eBWEmVkaroDNzBLxHLCZWSJeBWFmlkg9VcB+K7KZ5UpHZ0PFrRxJ/yxpjaTVkpZI2lfSVEn3SNog6QZJw6qN1QnYzHIlovJWiqRG4MPAkRHxWmAIcAZwGfCViDgU+B9gXrWxOgGbWa50hipuFRgKjJA0FNgP2AocB3w3278YmF1trE7AZpYrEaq4SWqWtKqoNb88TrQBXwYep5B4nwXuBZ6JiPbssFagsdpYfRHOzHKlL6sgIqIFaOlpn6TRwCxgKvAM8B1gRv8jfNmAJ+Bxt2wY6FNYHXpxy89Th2A5VeHUQiX+DtgYEU8ASPoe8FZglKShWRXcBLRVewJPQZhZrtRwFcTjwNGS9pMk4HhgLfAT4LTsmLnATdXG6gRsZrkSfWglx4m4h8LFtt8AD1LIly3AJ4CPStoAHAxcVW2sngM2s1yp4RQEEXExcHG37keBo2oxvhOwmeWKH8ZjZpZIHb0U2QnYzPIlcAVsZpZEu6cgzMzScAVsZpaI54DNzBJxBWxmlogrYDOzRDpcAZuZpVFHbyRyAjazfOl0BWxmlkYdvRTZCdjM8sUX4czMEumUpyDMzJLoSB1AHzgBm1mueBWEmVkiXgVhZpaIV0GYmSVST1MQfimnmeVKZx9aOZJGSfqupIckrZN0jKQxku6QtD77OrraWJ2AzSxXOlR5q8DlwK0R8RrgCGAdcCGwIiKmASuy7ao4AZtZrtSqApZ0EPB2stfOR8SOiHgGmAUszg5bDMyuNlYnYDPLlb4kYEnNklYVteaioaYCTwBXS/qtpP+StD8wPiK2ZsdsA8ZXG6svwplZrvTllXAR0QK09LJ7KPBG4EMRcY+ky+k23RARIanqhReugM0sV2p4Ea4VaI2Ie7Lt71JIyL+XNBEg+7q92lidgM0sVzr60EqJiG3AZkmHZV3HA2uBZcDcrG8ucFO1sXoKwsxypcbrgD8EfFvSMOBR4FwKhetSSfOATcCcagd3AjazXKnl4ygj4j7gyB52HV+L8Z2AzSxX/DxgM7NE/CwIM7NE6ulZEE7AZpYrfiC7mVkinXU0CeEEbGa54otwZmaJ1E/96wRsZjnjCtjMLJH26p+NM+icgM0sV+on/ToBm1nOeArCzCwRL0MzM0ukftKvE7CZ5YynIMzMEumooxrYCdjMcsUVsJlZIuEK2MwsDVfA9memn3AsCxZ8liENDSy8egn//qUrU4dkg+SiLyzgzl/8mjGjR/Hf134DgCuvupYbl93K6FEHAXDBP87l7W85ih/e9mOuvu7GXd/78CMb+c7C/+A1r35VktjrUa2XoUkaAqwC2iJipqSpwPXAwcC9wNkRsaOasZ2AB0FDQwNXXH4pM046k9bWrdz9q+X84Ie3s27d+tSh2SCYfdK7OOs9p/Cpz315t/6zT5/NuWedtlvfzOnHMXP6cUAh+X74ws86+fbRAExAXACsA0Zm25cBX4mI6yV9A5gHfL2agf1a+kFw1JvewCOPPMbGjY+zc+dOli69iVNOnp46LBskR/716zho5IF9/r7ld/yME//uHQMQUb61ExW3ciQ1Ae8G/ivbFnAc8N3skMXA7GpjdQIeBJMaJ7C5dcuu7da2rUyaNCFhRLYnWHLjDzj1nH/ioi8s4Nnn/vBn+29d8TNOetexgx9YnYs+/JLULGlVUWvuNtxXgfm8PLV8MPBMRLRn261AY7WxVp2AJZ1bYt+uH6qz8/lqT2GWW6ef+m5uWbqQGxddyV8cPIYv/f9v7rb/gTUPMWLffZn2yilpAqxjnX1oEdESEUcWtZaucSTNBLZHxL0DFWt/KuB/7W1H8Q/V0LB/P06RD1vatjG5adKu7abGiWzZsi1hRJba2DGjGTJkCA0NDZx2yomsXvvwbvtv+ZGnH6rVlwq4jLcCp0h6jMJFt+OAy4FRkrqunzUBbdXGWjIBS3qgl/YgML7ak+5tVq66j0MPncqUKZPZZ599mDNnFj/44e2pw7KEnnjy6V2fV/zslxz6ylfs2u7s7OS2H//cCbhKfamAS4mIT0ZEU0RMAc4AfhwR7wV+AnRdPZ0L3FRtrOVWQYwHpgP/061fwC+rPenepqOjgws+chHLb76OIQ0NLFp8A2u7VTyWX/9y8RdZ+dsHeOaZ5zh+9vv44LyzWfnbB/jd+kdB0DhhPBfP//Cu41fdt5oJ48YyuXFiwqjrV0cM+I0YnwCul/R54LfAVdUOpCgRrKSrgKsj4q4e9l0XEWeVO8HQYY31c1uKDZoXt/w8dQi2B9pn7CvV3zHOesWpFeec6zZ9v9/n64+SFXBEzCuxr2zyNTMbbL4V2cwsEd+KbGaWiN+IYWaWiKcgzMwSGYRVEDXjBGxmueIpCDOzRHwRzswsEc8Bm5kl4ikIM7NESt3du6dxAjazXPFr6c3MEvEUhJlZIp6CMDNLxBWwmVkiXoZmZpaIb0U2M0vEUxBmZok4AZuZJVJPqyD681p6M7M9TidRcStF0mRJP5G0VtIaSRdk/WMk3SFpffZ1dLWxOgGbWa5EH36V0Q58LCIOB44GzpN0OHAhsCIipgErsu2qeArCzHKlI2rzQMqI2ApszT7/QdI6oBGYBRybHbYY+CmFV9X3mStgM8uViKi4SWqWtKqoNfc0pqQpwBuAe4DxWXIG2AaMrzZWV8Bmlit9WQURES1AS6ljJB0A3Ah8JCKek1T8/SGp6qt+roDNLFdqOAeMpH0oJN9vR8T3su7fS5qY7Z8IbK82VidgM8uVzoiKWykqlLpXAesiYkHRrmXA3OzzXOCmamP1FISZ5UoNnwXxVuBs4EFJ92V9nwK+CCyVNA/YBMyp9gROwGaWKzVcBXEXoF52H1+LczgBm1mulJta2JM4AZtZrvhxlGZmibgCNjNLxBWwmVkiHdGROoSKOQGbWa7U0+MonYDNLFf8QHYzs0RcAZuZJeJVEGZmiXgVhJlZIrW6FXkwOAGbWa54DtjMLBHPAZuZJeIK2MwsEa8DNjNLxBWwmVkiXgVhZpaIL8KZmSVST1MQfiuymeVKjV9LP0PS7yRtkHRhrWN1BWxmuVKrCljSEOBK4F1AK7BS0rKIWFuTE+AEbGY5U8M54KOADRHxKICk64FZQP0k4PYdbb291nmvI6k5IlpSx2F7Fv+5qK2+5BxJzUBzUVdL0X+LRmBz0b5W4M39j/BlngMeXM3lD7G9kP9cJBIRLRFxZFEb1L8InYDNzHrWBkwu2m7K+mrGCdjMrGcrgWmSpkoaBpwBLKvlCXwRbnB5ns964j8Xe6CIaJd0PnAbMARYGBFrankO1dOiZTOzPPEUhJlZIk7AZmaJOAEPkoG+pdHqj6SFkrZLWp06FkvDCXgQFN3SeCJwOHCmpMPTRmV7gEXAjNRBWDpOwINj1y2NEbED6Lql0fZiEXEn8HTqOCwdJ+DB0dMtjY2JYjGzPYQTsJlZIk7Ag2PAb2k0s/rjBDw4BvyWRjOrP07AgyAi2oGuWxrXAUtrfUuj1R9JS4BfAYdJapU0L3VMNrh8K7KZWSKugM3MEnECNjNLxAnYzCwRJ2Azs0ScgM3MEnECNjNLxAnYzCyR/wWVy4HLQacfmAAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light",
      "tags": []
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.heatmap(con_metric, annot=True, fmt='d')\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "JqJdjlveSo7s",
    "outputId": "573e535a-e727-416d-daf2-bda57a91444d"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,\n",
       "    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',\n",
       "    max_iter=-1, probability=False, random_state=None, shrinking=True,\n",
       "    tol=0.001, verbose=False)"
      ]
     },
     "execution_count": 45,
     "metadata": {
      "tags": []
     },
     "output_type": "execute_result"
    }
   ],
   "source": [
    "classifier = SVC(kernel='linear')\n",
    "classifier.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {
    "id": "z-9qAxWqSpX3"
   },
   "outputs": [],
   "source": [
    "y_pred = classifier.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "3h34XM2nSpqe",
    "outputId": "db675fe2-b181-4371-e261-e124f3773afe"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.61328125\n",
      "0.61328125\n",
      "0.5\n",
      "0.7602905569007264\n"
     ]
    }
   ],
   "source": [
    "from sklearn import metrics\n",
    "print(metrics.accuracy_score(y_test, y_pred))\n",
    "print(metrics.precision_score(y_test,y_pred))\n",
    "print(metrics.roc_auc_score(y_test,y_pred))\n",
    "print(metrics.f1_score(y_test,y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "X63gfIItSp2x",
    "outputId": "83e208fb-8d70-47f3-8467-a3f2641a51d0"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[  0,  99],\n",
       "       [  0, 157]])"
      ]
     },
     "execution_count": 48,
     "metadata": {
      "tags": []
     },
     "output_type": "execute_result"
    }
   ],
   "source": [
    "con_metric = metrics.confusion_matrix(y_test, y_pred)\n",
    "con_metric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 281
    },
    "id": "zOF52vK6TISG",
    "outputId": "3fd75274-5c2c-4efc-9fd5-a21046e7306f"
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWAAAAEICAYAAABhxi57AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAXYElEQVR4nO3dfbxVZZ338c/3gCA+ICAjDwcMCrJxapy6zbSmxnQSMBR85eBDKXlzz7mbtOyuhqx8pVPZ5NRt6dxWcxoRzEQpa6AkH6LSrDSwfODBBEXkHCB8GLXUhHP27/5jr4Ob0zl777PP5lzsxffN63qdva61zrV+B/HHj2tday1FBGZmNvCaUgdgZravcgI2M0vECdjMLBEnYDOzRJyAzcwScQI2M0vECdh2kTRM0g8kPSfpO/0Y572Sbq9nbClI+pGkuanjsPxyAm5Aks6WtErSHyVtzRLF39Zh6NOBMcChEfEPtQ4SEd+OiJPqEM9uJB0vKSR9v1v/UVn/z6oc51JJ11c6LiJmRMSiGsM1q8gJuMFI+ijwVeALFJPl4cDXgFl1GP5VwCMR0VGHsfaUJ4HjJB1a0jcXeKReJ1CR/9+wPS8i3BqkAYcAfwT+ocwxQykm6C1Z+yowNNt3PNAGfAzYDmwFzsv2/QuwA9iZnWMecClwfcnYk4AABmfb7wceA/4AbATeW9J/d8n3vRVYCTyXfX1ryb6fAZ8DfpGNczswupefrSv+bwDnZ32DgHbgM8DPSo69EtgMPA/cB7w965/e7ed8oCSOy7I4XgKmZH3/K9v/deDmkvEvB1YASv3nwq1xm/+WbyzHAfsD3y9zzKeBY4G/AY4CjgEuLtk/lmIib6aYZK+WNDIiLqFYVd8UEQdFxDXlApF0IHAVMCMiDqaYZO/v4bhRwC3ZsYcCVwC3dKtgzwbOAw4DhgAfL3du4Drg3OzzNGA1xb9sSq2k+HswCrgB+I6k/SPi1m4/51El33MO0AIcDGzqNt7HgDdIer+kt1P8vZsbEb6X32rmBNxYDgWeivJTBO8FPhsR2yPiSYqV7Tkl+3dm+3dGxHKKVeARNcZTAF4vaVhEbI2INT0c825gfUR8KyI6ImIx8DBwSskx10bEIxHxErCEYuLsVUT8Ehgl6QiKifi6Ho65PiKezs75fyn+y6DSz7kwItZk37Oz23gvUvx9vAK4HvhQRLRVGM+sLCfgxvI0MFrS4DLHjGf36m1T1rdrjG4J/EXgoL4GEhEvAGcAHwC2SrpF0uuqiKcrpuaS7W01xPMt4ALgnfTwLwJJH5e0LlvR8SzFqn90hTE3l9sZEfdSnHIRxb8ozPrFCbix/Ap4GZhd5pgtFC+mdTmcP//nebVeAA4o2R5bujMibouIdwHjKFa136winq6Y2muMqcu3gA8Cy7PqdJdsimA+MAcYGREjKM4/qyv0XsYsO50g6XyKlfSWbHyzfnECbiAR8RzFi01XS5ot6QBJ+0maIenfssMWAxdL+gtJo7PjKy656sX9wDskHS7pEOCTXTskjZE0K5sLfpniVEahhzGWA6/Nls4NlnQGcCTwwxpjAiAiNgJ/R3HOu7uDgQ6KKyYGS/oMMLxk/++BSX1Z6SDptcDngfdRnIqYL6nsVIlZJU7ADSabz/woxQtrT1L8Z/MFwH9lh3weWAU8CDwE/Cbrq+VcdwA3ZWPdx+5JsymLYwvwDMVk+E89jPE0MJPiRaynKVaOMyPiqVpi6jb23RHRU3V/G3ArxaVpm4A/sfv0QtdNJk9L+k2l82RTPtcDl0fEAxGxHvgU8C1JQ/vzM9i+Tb6Ia2aWhitgM7NEnIDNzBJxAjYzS8QJ2MwskXIL+utzgiHNvspnf2b7jCmpQ7C90Kild6ryUeXtfOqxqnPOfqNf3e/z9YcrYDOzRPZ4BWxmNqAKnakjqJoTsJnlS+fe/Djr3TkBm1muRPR0R/zeyQnYzPKl4ARsZpaGK2Azs0R8Ec7MLBFXwGZmaYRXQZiZJeKLcGZmiXgKwswsEV+EMzNLxBWwmVkivghnZpaIL8KZmaUR4TlgM7M0PAdsZpaIpyDMzBJxBWxmlkjnztQRVM3vhDOzfCkUqm8VSFogabuk1T3s+5ikkDQ625akqyRtkPSgpDdVGt8J2MzyJQrVt8oWAtO7d0qaCJwEPFHSPQOYmrUW4OuVBncCNrN8qWMFHBF3Ac/0sOsrwHwgSvpmAddF0T3ACEnjyo3vBGxm+dKHBCypRdKqktZSaXhJs4D2iHig265mYHPJdlvW1ytfhDOzXIk+XISLiFagtdrjJR0AfIri9EO/OQGbWb7s2WVorwEmAw9IApgA/EbSMUA7MLHk2AlZX6+cgM0sX/bgjRgR8RBwWNe2pMeBoyPiKUnLgAsk3Qi8BXguIraWG89zwGaWL3VcBSFpMfAr4AhJbZLmlTl8OfAYsAH4JvDBSuO7AjazfKljBRwRZ1XYP6nkcwDn92V8J2AzyxffimxmlkiHH8huZpaGK2Azs0T8OEozs0RcAZuZJeIK2MwsEVfAZmaJeBWEmVkiEZWP2Us4AZtZvngO2MwsESdgM7NEfBHOzCyRzs7UEVTNCdjM8sVTEGZmiTgBm5kl4jlgM7M0ouB1wGZmaTTQFITfCWdm+dLZWX2rQNICSdslrS7p+5KkhyU9KOn7kkaU7PukpA2SfidpWqXxnYDNLF8KhepbZQuB6d367gBeHxF/DTwCfBJA0pHAmcBfZd/zNUmDyg3uBGxm+VLHBBwRdwHPdOu7PSK6nvhzDzAh+zwLuDEiXo6IjRTfjnxMufGdgAfItJOOZ83qu3h47d3M/+c+vTjVcmTozPcw/KprGf7vCxl6yukADJr0GoZf/jWGX3ktB336X2HYAYmjbHAR1bf++5/Aj7LPzcDmkn1tWV+vnIAHQFNTE1ddeRkzT3kfbzjqnZxxxmz+8i+npg7LBtigwycz9KSZPP/xD/D8hfMY8ubjaBrbzIEXzOfF6/6D5y88jx33/Jxhp52ZOtTG1ocKWFKLpFUlraXa00j6NNABfLvWUCuugpD0OoqldVcmbweWRcS6Wk+6rznmzW/k0UcfZ+PGJwBYsmQpp54yjXXr1ieOzAZS04RX0fnIOtjxMgA7Vz/AkOPeQdP4CXSseQCAjgdWMuzSL/PSDQtShtrY+rAMLSJagda+nkLS+4GZwIkRu0rpdmBiyWETsr5ela2AJX0CuBEQ8OusCVgs6aK+Br2vGt88ls1tW3Ztt7VvZfz4sQkjshQ6n9jI4CP/Gh08HIYMZcj/OJam0YfRuflx9nvL3wIw5K3vpGn0YYkjbXB1XAXRE0nTgfnAqRHxYsmuZcCZkoZKmgxMpZgze1WpAp4H/FVE7OwWwBXAGuCLvQTYArQAaNAhNDUdWOE0ZvlXaNvES9+7gYMv/TLx8p/o2LgBCp28cNXlHPiPH2bYnHPZ8etfEDt3Vh7MehV1XAcsaTFwPDBaUhtwCcVVD0OBOyQB3BMRH4iINZKWAGspTk2cHxFls3ylBFwAxgObuvWPy/b1qLSsHzykuXFuS9lDtrRvY+KE8bu2JzSPY8uWbQkjslR2/Hg5O368HIBh7/tHCk8/SaH9Cf5w6ccBaBo/gSFHH5cyxMZXxzvhIuKsHrqvKXP8ZcBl1Y5fKQF/BFghaT2vXN07HJgCXFDtSfZ1K1fdz5Qpk5k0aSLt7duYM2cW55zrlRD7Ih0ygnjuWZpGH8aQ497O8/M/uKsPiWFzzuVPty5LHWZjy8uzICLiVkmvpbiWrfQi3MpKpbW9orOzkws/cjHLb7mBQU1NLFx0E2vXPpI6LEvgoE98jqbhw4mODl74j68SL/yRoTPfw/4nnwbAjnvuYseK5YmjbHAN9CwIxR5+gZ2nIKwn22dMSR2C7YVGLb1T/R3jhc+cWXXOOfCzN/b7fP3hh/GYWb7kZQrCzKzhNNAUhBOwmeVKPZeh7WlOwGaWL66AzcwScQI2M0vEr6U3M0vD74QzM0vFCdjMLBGvgjAzS8QVsJlZIk7AZmZpRKenIMzM0nAFbGaWhpehmZml4gRsZpZI40wBl38rsplZo4mOQtWtEkkLJG2XtLqkb5SkOyStz76OzPol6SpJGyQ9KOlNlcZ3AjazfCn0oVW2EJjere8iYEVETAVWZNsAMyi+in4qxbfCf73S4E7AZpYrUYiqW8WxIu4CnunWPQtYlH1eBMwu6b8uiu4BRkgaV258J2Azy5c+VMCSWiStKmktVZxhTERszT5vA8Zkn5t55e3xAG288jLjHvkinJnlSl+WoUVEK9Ba87kiQlLNyy5cAZtZvtR3Drgnv++aWsi+bs/624GJJcdNyPp65QRsZrkSHdW3Gi0D5maf5wJLS/rPzVZDHAs8VzJV0SNPQZhZrtTzrfSSFgPHA6MltQGXAF8ElkiaB2wC5mSHLwdOBjYALwLnVRrfCdjM8qWOCTgizupl14k9HBvA+X0Z3wnYzHKlnhXwnuYEbGa54gRsZpZIdCp1CFVzAjazXHEFbGaWSBRcAZuZJeEK2MwskQhXwGZmSbgCNjNLpOBVEGZmafginJlZIk7AZmaJROO8FNkJ2MzyxRWwmVkiXoZmZpZIp1dBmJml4QrYzCwRzwGbmSXiVRBmZok0UgXstyKbWa50FpqqbpVI+j+S1khaLWmxpP0lTZZ0r6QNkm6SNKTWWJ2AzSxXIqpv5UhqBj4MHB0RrwcGAWcClwNfiYgpwH8D82qN1QnYzHKlEKq6VWEwMEzSYOAAYCtwAvDdbP8iYHatsToBm1muRKjqJqlF0qqS1vLKONEOfBl4gmLifQ64D3g2Ijqyw9qA5lpj9UU4M8uVvqyCiIhWoLWnfZJGArOAycCzwHeA6f2P8BVOwJbEwddcmzoEy6kqpxaq8ffAxoh4EkDS94C3ASMkDc6q4AlAe60n8BSEmeVKHVdBPAEcK+kASQJOBNYCPwVOz46ZCyytNVYnYDPLlehDKztOxL0UL7b9BniIYr5sBT4BfFTSBuBQ4JpaY/UUhJnlSh2nIIiIS4BLunU/BhxTj/GdgM0sV/wwHjOzRBropchOwGaWL4ErYDOzJDo8BWFmloYrYDOzRDwHbGaWiCtgM7NEXAGbmSXS6QrYzCyNBnojkROwmeVLwRWwmVkaDfRSZCdgM8sXX4QzM0ukIE9BmJkl0Zk6gD5wAjazXPEqCDOzRLwKwswsEa+CMDNLpJGmIPxSTjPLlUIfWiWSRkj6rqSHJa2TdJykUZLukLQ++zqy1lidgM0sVzpVfavClcCtEfE64ChgHXARsCIipgIrsu2aOAGbWa7UqwKWdAjwDrLXzkfEjoh4FpgFLMoOWwTMrjVWJ2Azy5W+JGBJLZJWlbSWkqEmA08C10r6raT/lHQgMCYitmbHbAPG1BqrL8KZWa705ZVwEdEKtPayezDwJuBDEXGvpCvpNt0QESGp5oUXroDNLFfqeBGuDWiLiHuz7e9STMi/lzQOIPu6vdZYnYDNLFc6+9DKiYhtwGZJR2RdJwJrgWXA3KxvLrC01lg9BWFmuVLndcAfAr4taQjwGHAexcJ1iaR5wCZgTq2DOwGbWa7U83GUEXE/cHQPu06sx/hOwGaWK34esJlZIn4WhJlZIo30LAgnYDPLFT+Q3cwskUIDTUI4AZtZrvginJlZIo1T/zoBm1nOuAI2M0uko/Zn4ww4J2Azy5XGSb9OwGaWM56CMDNLxMvQzMwSaZz06wRsZjnjKQgzs0Q6G6gGdgI2s1xxBWxmlki4AjYzS8MVsP2ZaScdzxVXfJZBTU0suHYx//alq1OHZAPk4i9cwV2/+DWjRo7gv67/BgBXX3M9Ny+7lZEjDgHgwv89l3e89Rh+eNtPuPaGm3d97yOPbuQ7C/6d1732NUlib0T1XoYmaRCwCmiPiJmSJgM3AocC9wHnRMSOWsZ2Ah4ATU1NXHXlZUw/+Sza2rZyz6+W84Mf3s66detTh2YDYPbJ7+Ls95zKpz735d36zzljNuedffpufTOnncDMaScAxeT74Ys+6+TbR3tgAuJCYB0wPNu+HPhKRNwo6RvAPODrtQzs19IPgGPe/EYeffRxNm58gp07d7JkyVJOPWVa6rBsgBz9N2/gkOEH9/n7lt9xJzP+/u/2QET51kFU3SqRNAF4N/Cf2baAE4DvZocsAmbXGqsT8AAY3zyWzW1bdm23tW9l/PixCSOyvcHim3/Aaef+Exd/4Qqee/4Pf7b/1hV3cvK7jh/4wBpc9OGXpBZJq0paS7fhvgrM55Wp5UOBZyOiI9tuA5prjbXmBCzpvDL7dv1QhcILtZ7CLLfOOO3d/GjJAm5eeDV/cegovvT/vrnb/gfXPMyw/fdn6qsnpQmwgRX60CKiNSKOLmmtXeNImglsj4j79lSs/amA/6W3HaU/VFPTgf04RT5sad/GxAnjd21PaB7Hli3bEkZkqY0eNZJBgwbR1NTE6afOYPXaR3bb/6Mfe/qhVn2pgCt4G3CqpMcpXnQ7AbgSGCGp6/rZBKC91ljLJmBJD/bSHgLG1HrSfc3KVfczZcpkJk2ayH777cecObP4wQ9vTx2WJfTkU8/s+rzizl8y5dWv2rVdKBS47Sc/dwKuUV8q4HIi4pMRMSEiJgFnAj+JiPcCPwW6rp7OBZbWGmulVRBjgGnAf3frF/DLWk+6r+ns7OTCj1zM8ltuYFBTEwsX3cTabhWP5dc/X/JFVv72QZ599nlOnP0+PjjvHFb+9kF+t/4xEDSPHcMl8z+86/hV969m7GGjmdg8LmHUjasz9viNGJ8AbpT0eeC3wDW1DqQoE6yka4BrI+LuHvbdEBFnVzrB4CHNjXNbig2Yl7b8PHUIthfab/Sr1d8xzn7VaVXnnBs2fb/f5+uPshVwRMwrs69i8jUzG2i+FdnMLBHfimxmlojfiGFmloinIMzMEhmAVRB14wRsZrniKQgzs0R8Ec7MLBHPAZuZJeIpCDOzRMrd3bu3cQI2s1zxa+nNzBLxFISZWSKegjAzS8QVsJlZIl6GZmaWiG9FNjNLxFMQZmaJOAGbmSXSSKsg+vNaejOzvU6BqLqVI2mipJ9KWitpjaQLs/5Rku6QtD77OrLWWJ2AzSxXog+/KugAPhYRRwLHAudLOhK4CFgREVOBFdl2TTwFYWa50hn1eSBlRGwFtmaf/yBpHdAMzAKOzw5bBPyM4qvq+8wVsJnlSkRU3SS1SFpV0lp6GlPSJOCNwL3AmCw5A2wDxtQaqytgM8uVvqyCiIhWoLXcMZIOAm4GPhIRz0sq/f6QVPNVP1fAZpYrdZwDRtJ+FJPvtyPie1n37yWNy/aPA7bXGqsTsJnlSiGi6laOiqXuNcC6iLiiZNcyYG72eS6wtNZYPQVhZrlSx2dBvA04B3hI0v1Z36eALwJLJM0DNgFzaj2BE7CZ5UodV0HcDaiX3SfW4xxOwGaWK5WmFvYmTsBmlit+HKWZWSKugM3MEnEFbGaWSGd0pg6hak7AZpYrjfQ4SidgM8sVP5DdzCwRV8BmZol4FYSZWSJeBWFmlki9bkUeCE7AZpYrngM2M0vEc8BmZom4AjYzS8TrgM3MEnEFbGaWiFdBmJkl4otwZmaJNNIUhN+KbGa5UufX0k+X9DtJGyRdVO9YXQGbWa7UqwKWNAi4GngX0AaslLQsItbW5QQ4AZtZztRxDvgYYENEPAYg6UZgFtA4CbhjR3tvr3Xe50hqiYjW1HHY3sV/LuqrLzlHUgvQUtLVWvLfohnYXLKvDXhL/yN8heeAB1ZL5UNsH+Q/F4lERGtEHF3SBvQvQidgM7OetQMTS7YnZH114wRsZtazlcBUSZMlDQHOBJbV8wS+CDewPM9nPfGfi71QRHRIugC4DRgELIiINfU8hxpp0bKZWZ54CsLMLBEnYDOzRJyAB8ievqXRGo+kBZK2S1qdOhZLwwl4AJTc0jgDOBI4S9KRaaOyvcBCYHrqICwdJ+CBseuWxojYAXTd0mj7sIi4C3gmdRyWjhPwwOjplsbmRLGY2V7CCdjMLBEn4IGxx29pNLPG4wQ8MPb4LY1m1nicgAdARHQAXbc0rgOW1PuWRms8khYDvwKOkNQmaV7qmGxg+VZkM7NEXAGbmSXiBGxmlogTsJlZIk7AZmaJOAGbmSXiBGxmlogTsJlZIv8f7Xt2HT9+uB0AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light",
      "tags": []
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.heatmap(con_metric, annot=True, fmt='d')\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "jQsAU6hbUx4Q"
   },
   "source": [
    "**OBSERVATION**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "Fuw38UaAUQZ6"
   },
   "source": [
    "**From all the above confusion matrix it is evident that svm with kernel rbf gives best results so using rbf kernel for deployment**\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "mD8Z9YVoUPHa",
    "outputId": "cbf4d623-7865-4610-82b1-999907b20039"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,\n",
       "    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',\n",
       "    max_iter=-1, probability=False, random_state=None, shrinking=True,\n",
       "    tol=0.001, verbose=False)"
      ]
     },
     "execution_count": 50,
     "metadata": {
      "tags": []
     },
     "output_type": "execute_result"
    }
   ],
   "source": [
    "classifier = SVC(kernel='rbf')\n",
    "classifier.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {
    "id": "M8xjN6duUPWY"
   },
   "outputs": [],
   "source": [
    "from pickle import dump\n",
    "dump(classifier,open(r'svm.pkl','wb'))"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "collapsed_sections": [],
   "name": "innomaticstask.ipynb",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
